### ISSUE TITLE
[solved] Packages apparently wrongly imported

### ISSUE THREAD

**Issue by quentinmarolleau** [adareau/HAL#101]
I had a bug at startup causing a crash: some packages of PyQt5 seemed to be wrongly imported. A quick fix apparently did the job... fc1485d380eb298289af5f139830598f03f5f437

**Comment by adareau** [comment]
J'avais corrigé ça en local chez moi, mais j'ai été trop lent à dégainer sur github (cf. hotfix/pyqt5-import-error).
Je vais utiliser ton fix du coup ;)

**Comment by adareau** [comment]
fixed in testing and devel
![image](https://user-images.githubusercontent.com/1842228/131675346-13d459f9-3396-430e-b800-f28999a413c0.png)
