### ISSUE TITLE
90° rotated images displayed

### ISSUE THREAD

**Issue by quentinmarolleau** [adareau/HAL#103]
![image](https://user-images.githubusercontent.com/30953121/131617211-07657239-d2f0-44da-ab5e-3d2f1b34c938.png)

Excuse me, wtf ??

**Comment by adareau** [comment]
Must be because the `RawCamData`data class is selected. You can choose the data type on the gui (and should use Xenics in your case). To ignore the `RawCamData`, add the following line in your config file:

```
[global]
ignored modules list = RawCamData
```

**Comment by quentinmarolleau** [comment]
well, I don't have the Xenics option in the list for "Data Type". What the `RawCamData` is intended to do ?

**Comment by adareau** [comment]
What is this bug ?

**Comment by adareau** [comment]
> well, I don't have the Xenics option in the list for "Data Type". What the `RawCamData` is intended to do ? If it sets (as it seems when reading it) the parameters like `name`, `scale` and whatever, we should use it for our own camera right ?

The RawCamData is just a "default" DataClass for loading picture (basically, it loads pngs). The point is to have a DataClass provided with HAL that works out of the box, without having to code your own picture class right away (and, when you do so, to provide an example).

I agree that the way it works is not ideal, but it is hard to provide **both** something that can load images out of the box and let the user provide their own classes...

**Comment by quentinmarolleau** [comment]
I was working on a He1 camera class, but I just realised that you actually already did it in a side repo https://github.com/adareau/HAL-modules
