### ISSUE TITLE
Improve ROI management

### ISSUE THREAD

**Issue by adareau** [adareau/HAL#25]
The ROI management has to be improved / finished:

- [x] select the current ROI using the "selectRoiComboBox". This should change the "selected_ROI" value sent, for instance, to the updatePlot() method of Display classes
- [x] rename / delete the current ROI
- [x] reset all ROIs

For the interface with the ROIs, make sure to use the dedicated methods of the display classes:

- getROINames()
- removeROI()
- updateROI()
- etc..

**Comment by quentinmarolleau** [comment]
#42

**Comment by adareau** [comment]
good job ;)
