### ISSUE TITLE
Add a "today" button for day browsing

### ISSUE THREAD

**Issue by adareau** [adareau/HAL#3]
Add a button "today". When clicked, set calendar datePicker to current date, and refresh current folder

**Comment by QuantumVictor** [comment]
This has been done on the feat/TodayButton branch however their still is an issue with the text.

**Comment by adareau** [comment]
OK, let's check whether we can merge it to devel, and we'll fix the test issue after that

**Comment by adareau** [comment]
I can now close this issue. Thank you @QuantumVictor :smile:
