### ISSUE TITLE
Add a "merge dataset" or a "add to dataset" feature

### ISSUE THREAD

**Issue by adareau** [adareau/HAL#4]
**Option 1:** *MERGE*
all selected dataset are merged into one new dataset. Potential problem: how to handle the case where some datasets are in the current folder and the other ones in the "favorite" folder ?

**Option 2:** *ADD TO DATASET*
all selected runs are added to the current dataset. Potentially harder to implement (?)

**NB** both options could be implemented, actually

**Comment by charlieleprince** [comment]
- [ ] add to dataset button
- [ ] button to check what is in the dataset
