### ISSUE TITLE
Improve the behaviour when the run list is refreshed

### ISSUE THREAD

**Issue by adareau** [adareau/HAL#53]
There are two "bugs" when refreshing the list of runs:

- [x] the current index of the run list is not conserved (set to None)
- [x] the selected set list is not conserved

**Comment by adareau** [comment]
Should be OK now. @quentinmarolleau, can you confirm that it works as expected ?

**Comment by quentinmarolleau** [comment]
> Should be OK now. @quentinmarolleau, can you confirm that it works as expected ?

It works fine! I intergrated your changes into ROI branch, and it actually fixed most of my issues.
